"""add inage fields to message

Revision ID: 0a80ac9b4d37
Revises: 404ac4542471
Create Date: 2026-04-12 13:43:31.216265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a80ac9b4d37'
down_revision = '404ac4542471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_iv', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_data')
        batch_op.drop_column('image_iv')
        batch_op.drop_column('image_mime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_mime', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_iv', sa.VARCHAR(length=24), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.TEXT(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_iv')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
