"""add email confirmation fields

Revision ID: 1b46f8cace6b
Revises: b1495bcc4036
Create Date: 2026-04-07 22:59:54.640566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b46f8cace6b'
down_revision = 'b1495bcc4036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('code_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_expires')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
